# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.cache/wt [current_project]
set_property parent.project_path /home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/Multiplexer_4way.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/Generic_counter.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/Decimal_decoder.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/MouseTransmitter.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/MouseReceiver.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/MouseMasterSM.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/DisplayInterface.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/MouseTransceiver.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/ALU.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/VGA_Sig_Gen.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/Frame_Buffer.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/LedPeripheral.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/Seg7Peripheral.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/BusInterfaceMouse.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/Timer.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/ROM.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/RAM.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/VGA_Driver.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/Microprocessor.v}
  {/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/sources_1/imports/testing src code/TopModule.v}
}
read_xdc {{/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/constrs_1/imports/testing src code/constraint.xdc}}
set_property used_in_implementation false [get_files {{/home/s2736992/InteracingVGA_Mouse/InteracingVGA_Mouse.srcs/constrs_1/imports/testing src code/constraint.xdc}}]

synth_design -top Top -part xc7a35ticpg236-1L
write_checkpoint -noxdef Top.dcp
catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
