# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.cache/wt [current_project]
set_property parent.project_path C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/MouseTransmitter.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/GenericCounter.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/MUX.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/MouseReciever.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/MouseMasterSM.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/SevenSegment.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/SevenSegmentWrapper.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/VGA_Sig_Gen.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/MouseTransceiver.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/Frame_Buffer.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/ALU.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/BusInterfaceMouse.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/BusInterfaceSevenSegment.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/ROM.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/BusInterfaceLED.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/VGA_Driver.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/Timer.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/Processor.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/RAM.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/new/BusInterfaceSwitch.v
  C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/sources_1/imports/Projekt-mouse/TopModule.v
}
read_xdc C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/constrs_1/imports/Projekt-mouse/MouseInterface.xdc
set_property used_in_implementation false [get_files C:/Users/s2736992/Final_VGA_MOUSE/Final_VGA_MOUSE.srcs/constrs_1/imports/Projekt-mouse/MouseInterface.xdc]

synth_design -top TopModule -part xc7a35tcpg236-1
write_checkpoint -noxdef TopModule.dcp
catch { report_utilization -file TopModule_utilization_synth.rpt -pb TopModule_utilization_synth.pb }
